PREFIX noa: <http://teleios.di.uoa.gr/ontologies/noaOntology.owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX strdf: <http://strdf.di.uoa.gr/ontology#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX gag: <http://geo.linkedopendata.gr/greekadministrativeregion/ontology#>

SELECT ?h  (strdf:transform(?hGeo, <http://www.opengis.net/def/crs/EPSG/0/4326>) AS ?geo) ?conf ?muni
WHERE { 
?h   noa:hasGeometry ?hGeo ;
     noa:hasAcquisitionTime ?hAcquisitionTime ; 
     noa:producedFromProcessingChain ?hProcessingChain ; 
     noa:isDerivedFromSensor "SENSOR"^^xsd:string ;
     noa:hasConfidence ?conf ;
     gag:hasMunicipality ?muni .
     FILTER(?hProcessingChain = "PROCESSING_CHAIN" || ?hProcessingChain = "PROCESSING_CHAIN-TimePersistence") .
     FILTER("MIN_ACQUISITION_TIME"^^xsd:dateTime <= ?hAcquisitionTime && ?hAcquisitionTime <= "MAX_ACQUISITION_TIME"^^xsd:dateTime ) .
     OPTIONAL {?h noa:isDiscarded ?disc }.
     FILTER (!bound(?disc)) .
}
