# discover hotspots that were deleted because they lie in sea
PREFIX noa: <http://teleios.di.uoa.gr/ontologies/noaOntology.owl#> 
PREFIX strdf: <http://strdf.di.uoa.gr/ontology#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?h (strdf:transform(?hGeo, <http://www.opengis.net/def/crs/EPSG/0/4326>) AS ?geo) ("Sea inconsistency" as ?refinement)
WHERE { 
    ?h   noa:hasGeometry ?hGeo ;
         noa:hasAcquisitionTime "TIMESTAMP"^^xsd:dateTime ;
         noa:refinedBy noa:seaInconsistency .
}
